import Navbar from "@/components/layout/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function FeedLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <body>
        <Navbar />
        {children}
      </body>
  )
}
